### ISSUE TITLE
Datepicker dates are not coming properly

### ISSUE THREAD

**Issue by swapneshk** [jkuri/ngDatepicker#10]
I am trying your demo for the project so I used the demo first, but looks like your date row creation logic for the month is not correct as in many cases 1st of the month is not showing. Please check attached screenshot -

Following more months, you can investigate -
May 2016, Jan 2017, Oct 2017 etc

![image](https://cloud.githubusercontent.com/assets/7931873/11434825/ccf7bb1a-94f8-11e5-8223-a473d7e50828.png)

**Comment by jkuri** [comment]
Thanks for noticing. Will fix this as soon as I will have time and inform
you. Thanks again.

Re

**Comment by ghost** [comment]
Hello swapneshk, 

changing line 10 to this:

``` javascript
scope.firstWeekDaySunday = scope.$eval(attrs.firstWeekDaySunday) || true;
```

and line 37 to this:

``` javascript
if (firstWeekDay !== 0) {
    n -= firstWeekDay - 1;
} else if (firstWeekDay == 0) {
    n -= firstWeekDay + 6;
}
```

of the 'ngDatepicker.js' file should fix your problem.

**Comment by mickeychu** [comment]
@cato1011 I'm sorry but line 10 of what file? Could you please be more specific?

**Comment by jkuri** [comment]
I merged some pull request which should fix this issue. Please someone try and let me know if it's working properly so I can close this issue. Thanks.

**Comment by KrisTemmerman** [comment]
Can confirm the fix works

**Comment by jkuri** [comment]
Ok, closing.
