### ISSUE TITLE
Display input elements inline

### ISSUE THREAD

**Issue by ricardoduarte** [jkuri/ngDatepicker#2]
Hi,

Congratulations for your ngDatePicker. It is a very good directive.

It would be great if we could display input elements inline.

For example, in my application, I want two datepicker elements side-by-side and I can't do that.

Sorry for my poor english, I'm a brazilian developer.

**Comment by ricardoduarte** [comment]
Don't worry about that. I fixed my problem with css float property.

**Comment by jkuri** [comment]
Good.
