### ISSUE TITLE
Is there any way to set the initial date?

### ISSUE THREAD

**Issue by ricardoduarte** [jkuri/ngDatepicker#4]

**Comment by jkuri** [comment]
Please see [https://github.com/jkuri/ngDatepicker/pull/3]

**Comment by jkuri** [comment]
@ricardoduarte please check out my last commit. That should work for you.

**Comment by ricardoduarte** [comment]
@jkuri Hi again.

I tested your last commit and it worked fine for me, but I have 2 directives in the same page and they seems somehow interconnected. They have the same date and when I click on one input the calendar opens in both of them. Weird!

I'm trying to assemble an example in jsfiddle to show you.

**Comment by ricardoduarte** [comment]
I found the problem.

Please, see the pull request #6

**Comment by jkuri** [comment]
Cool. Merged.
